--insert datas on tables by ntentie
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(001,'ABA',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(002,'Ado',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(003,'Anas',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(004,'bom',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(005,'balo',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(006,'bakosi',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(007,'bason',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(008,'cadin',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(009,'calvi',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(010,'cavou',123);