--insert datas on tables by ntentie
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'ABA',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'Ado',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'Anas',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'bom',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'balo',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'bakosi',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'bason',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'cadin',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'calvi',123);
INSERT INTO users(USER_ID,USER_NAME,USER_PASSWORD)values(1,'cavou',123);