--@constrains.unique
--@constraints.check
@objects/tables/constraints/fk/constrains_fk_academic_exp
@objects/tables/constraints/fk/constrains_fk_tables_videos
@objects/tables/constraints/fk/constrains_fk_tables_users
@objects/tables/constraints/fk/constrains_fk_tables_skills
@objects/tables/constraints/fk/constrains_fk_tables_projects
@objects/tables/constraints/fk/constrains_fk_tables_profile
@objects/tables/constraints/fk/constrains_fk_tables_professional_exp
@objects/tables/constraints/fk/constrains_fk_tables_pdf
@objects/tables/constraints/fk/constrains_fk_tables_other_files
@objects/tables/constraints/fk/constrains_fk_tables_other_exp
@objects/tables/constraints/fk/constrains_fk_tables_media
@objects/tables/constraints/fk/constrains_fk_tables_level_project
@objects/tables/constraints/fk/constrains_fk_tables_language
@objects/tables/constraints/fk/constrains_fk_tables_info_add
@objects/tables/constraints/fk/constrains_fk_tables_images
@objects/tables/constraints/fk/constrains_fk_tables_hobby_type
@objects/tables/constraints/fk/constrains_fk_tables_hobby
@objects/tables/constraints/fk/constrains_fk_tables_files
@objects/tables/constraints/fk/constrains_fk_tables_experiences
@objects/tables/constraints/fk/constrains_fk_tables_community_exp

